- uses: cschleiden/replace-tokens@v1
  with:
        files: '["**/*.cs"]'
  env:
    connectionString: Server=myServerAddress;Database=myDataBase;User Id=myUsername;Password=myPassword;
    epicorUrl: tcp:/someurl
    someVariable: SubbedByGithubActions
    anotherVariable: ChangedByGithubActions
